import type { ServerEntry, ServerStatus, ServerGroup, LocalServerConfig } from '../../types/server'
import { minecraftAPI } from '../../api/tauri-bridge'

export function createServerEntry(name: string, address: string, port: number = 25565): ServerEntry {
  return {
    id: `srv-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name,
    address,
    port,
    tags: [],
    addedAt: Date.now(),
    playCount: 0,
    isFavorite: false,
  }
}

export function parseServerAddress(input: string): { host: string; port: number } {
  const trimmed = input.trim()
  if (trimmed.includes(':')) {
    const parts = trimmed.split(':')
    return { host: parts[0], port: parseInt(parts[1]) || 25565 }
  }
  return { host: trimmed, port: 25565 }
}

export function formatServerAddress(host: string, port: number): string {
  return port === 25565 ? host : `${host}:${port}`
}

export function sortServers(servers: ServerEntry[], sortBy: 'name' | 'lastPlayed' | 'playCount' | 'ping' = 'name'): ServerEntry[] {
  const sorted = [...servers]
  switch (sortBy) {
    case 'name':
      sorted.sort((a, b) => a.name.localeCompare(b.name))
      break
    case 'lastPlayed':
      sorted.sort((a, b) => (b.lastPlayedAt || 0) - (a.lastPlayedAt || 0))
      break
    case 'playCount':
      sorted.sort((a, b) => b.playCount - a.playCount)
      break
  }
  const favorites = sorted.filter(s => s.isFavorite)
  const others = sorted.filter(s => !s.isFavorite)
  return [...favorites, ...others]
}

export function filterServersByGroup(servers: ServerEntry[], groupId: string | undefined, groups: ServerGroup[]): ServerEntry[] {
  if (!groupId || groupId === 'all') return servers
  return servers.filter(s => s.groupId === groupId)
}

export function filterServersByTag(servers: ServerEntry[], tag: string): ServerEntry[] {
  return servers.filter(s => s.tags.includes(tag))
}

export function searchServers(servers: ServerEntry[], query: string): ServerEntry[] {
  const q = query.toLowerCase()
  return servers.filter(s =>
    s.name.toLowerCase().includes(q) ||
    s.address.toLowerCase().includes(q) ||
    s.tags.some(t => t.toLowerCase().includes(q))
  )
}

export function createServerGroup(name: string, color?: string, icon?: string): ServerGroup {
  return {
    id: `grp-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name,
    color,
    icon,
    sortOrder: 0,
    collapsed: false,
  }
}

export function createDefaultLocalServerConfig(name: string, gameVersion: string, serverDir: string): LocalServerConfig {
  return {
    id: `lsrv-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name,
    gameVersion,
    serverType: 'vanilla',
    port: 25565,
    maxPlayers: 20,
    difficulty: 'normal',
    gameMode: 'survival',
    motd: `A Bonjour Server - ${name}`,
    onlineMode: true,
    pvpEnabled: true,
    spawnAnimals: true,
    spawnMonsters: true,
    serverDir,
    status: 'stopped',
    autoConnectClient: true,
  }
}

export function generateServerProperties(config: LocalServerConfig): string {
  const lines: string[] = [
    `# Minecraft server properties - generated by Bonjour Launcher`,
    `enable-jmx-monitoring=false`,
    `rcon.port=25575`,
    `level-name=world`,
    `gamemode=${config.gameMode}`,
    `enable-command-block=false`,
    `enable-query=false`,
    `generator-settings={}`,
    `enforce-secure-profile=true`,
    `level-type=minecraft\\:normal`,
    `spawn-npcs=true`,
    `spawn-animals=${config.spawnAnimals}`,
    `snooper-enabled=true`,
    `difficulty=${config.difficulty}`,
    `function-permission-level=2`,
    `network-compression-threshold=256`,
    `max-tick-time=60000`,
    `require-resource-pack=false`,
    `use-native-transport=true`,
    `max-players=${config.maxPlayers}`,
    `online-mode=${config.onlineMode}`,
    `enable-status=true`,
    `allow-flight=false`,
    `initial-disabled-packs=`,
    `broadcast-rcon-to-ops=true`,
    `view-distance=10`,
    `server-ip=`,
    `resource-pack-prompt=`,
    `allow-nether=true`,
    `server-port=${config.port}`,
    `enable-rcon=false`,
    `sync-chunk-writes=true`,
    `op-permission-level=4`,
    `prevent-proxy-connections=false`,
    `hide-online-players=false`,
    `resource-pack=`,
    `entity-broadcast-range-percentage=100`,
    `simulation-distance=10`,
    `rcon.password=`,
    `player-idle-timeout=0`,
    `force-gamemode=false`,
    `rate-limit=0`,
    `hardcore=false`,
    `white-list=false`,
    `broadcast-console-to-ops=true`,
    `pvp=${config.pvpEnabled}`,
    `spawn-monsters=${config.spawnMonsters}`,
    `max-world-size=29999984`,
    `resource-pack-sha1=`,
    `spawn-protection=16`,
    `max-chained-neighbor-updates=1000000`,
    `initial-enabled-packs=vanilla`,
    `motd=${config.motd}`,
  ]
  if (config.seed) {
    lines.push(`level-seed=${config.seed}`)
  }
  return lines.join('\n')
}

export async function pingServerStatus(host: string, port: number): Promise<ServerStatus> {
  try {
    const result = await minecraftAPI.pingServer(host, port)
    return {
      online: result.online ?? false,
      host,
      port,
      version: result.version ?? '',
      protocol: result.protocol ?? 0,
      playersOnline: result.playersOnline ?? 0,
      playersMax: result.playersMax ?? 0,
      playerList: result.playerList ?? [],
      motd: result.description ?? '',
      pingMs: result.latencyMs ?? -1,
      lastChecked: Date.now(),
    }
  } catch {
    return {
      online: false,
      host,
      port,
      version: '',
      protocol: 0,
      playersOnline: 0,
      playersMax: 0,
      playerList: [],
      motd: '',
      pingMs: -1,
      lastChecked: Date.now(),
    }
  }
}

export function classifyModSide(modFileName: string): 'client' | 'server' | 'both' {
  const clientOnlyPatterns = [
    /optifine/i, /sodium/i, /lithium/i, /iris/i, /phosphor/i,
    /betterfps/i, /fpsplus/i, /chunkanimator/i,
    /customcrosshair/i, /damageindicator/i, /minimap/i,
    /journeymap/i, /xaero/i, /voxelmap/i, /mapwriter/i,
    /neat/i, /waila/i, /hwyla/i, /jade/i, /theoneprobe/i,
    /appleskin/i, /jei/i, /rei/i, /emi/i,
    /inventoryhud/i, /itemscroller/i, /mousewheelie/i,
    /shulkerboxtooltip/i, /inventario/i,
    /soundfilters/i, /presencefootsteps/i, /dynamic surroundings/i,
    /visualworkbench/i, /concretepowdertoblock/i,
    /waila/i, /hwyla/i, /jade/i,
  ]
  const serverOnlyPatterns = [
    /worldguard/i, /worldedit/i, /essentials/i, /luckperms/i,
    /vault/i, /economy/i, /permissions/i, /coreprotect/i,
    /logblock/i, /griefprevention/i, /towny/i,
  ]

  for (const p of clientOnlyPatterns) {
    if (p.test(modFileName)) return 'client'
  }
  for (const p of serverOnlyPatterns) {
    if (p.test(modFileName)) return 'server'
  }
  return 'both'
}
